### ISSUE TITLE
Push Notifications mediator message failure on iOS after Credo updates

### ISSUE THREAD

**Issue by bryce-mcmath** [bcgov/bc-wallet-mobile#1959]
### Description
Since the Credo updates we now see error logs related to push notifications on iOS, like the following:
```
PushNotificationsFcmSetDeviceInfoMessage: Failed to validate class.\nAn instance of PushNotificationsFcmSetDeviceInfoMessage has failed the validation:\n - property devicePlatform has failed the following constraints: devicePlatform must be a string \n
```

`devicePlatform` doesn't appear in the wallet codebase anywhere so I'm not yet sure what's causing the issue.

Worth checking with the mediator team to see if they updated any dependencies recently.

**Comment by bryce-mcmath** [comment]
The issue has been fixed and push notifications are working again, but there is still some error logs related to validation of the response summarized in the below ticket:
#1976

**Comment by jleach** [comment]
Bryce McMath @bryce.mcmath
2:04 PM
It's sent to and then from the mediator, both with a similar payload. The 'to' message has been fixed, which fixed the push notifications not working, but the return 'from' message is still missing device_platform so it creates an error in the wallet logs. silent error for the user, they don't see anything. We don't really use the return message so it's not that important, but the mediator will just have to be updated at some point to include that part of the payload in it's response
